"""Add genre field to Movie model

Revision ID: ae4ff80a326a
Revises: 0ed23d75bab6
Create Date: 2024-12-05 15:08:38.161263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4ff80a326a'
down_revision = '0ed23d75bab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('genre')
    # ### end Alembic commands ###
